### ISSUE TITLE
Courses don't show up on scheduler

### ISSUE THREAD

**Issue by JKobyP** [hacsoc/the_jolly_advisor#205] opened 2016-03-06 14:25 UTC
To reproduce:

1. Go to advise.case.edu/scheduler
2. Add a course
3. Observe that the schedule remains blank

It seems that the courses _are_ being selected, because once you've "added" a course they disappear from the list. But the events do not show up on the schedule.

**Comment by ajm188** [comment] 2016-03-06 15:41
I am also seeing this behavior in both chrome and firefox. Not sure what the issue is yet.

**Comment by JKobyP** [comment] 2016-07-12 01:23
I'm no longer observing this

**Comment by ajm188** [comment] 2016-07-12 13:20
Welp, let's close it for now! 😛

**Closed by ajm188** 2016-07-12 13:20 UTC
Labels: bug
